### PR TITLE
Add horizontal force toggle.

### PR DESCRIPTION
**Pull request by FeepingCreature**
Add engine setting: "Horizontal Force". Defaults to on. If horizontal force is off, the engine only exerts force upwards/downwards.

For instance, when a huge-ass mining drill with eight hover engines wants to take a left turn through a too-small left curve, it's probably a good idea to only turn on horizontal force on the two left center engines. Otherwise, phantom forces arising from misalignment between the engines and the rails would probably cause the mining train to derail dramatically, forcing many many reloads.

You know, in theory.

(I added a commit with your mod changes from Steam too.)

edit: Oh yeah I turned off curve leaning too, it was a stupid idea.

### CODE REVIEW

**Comment by FeepingCreature** [comment]
Added an illustration. 
hoverrail_problem

**Comment by Izion** [comment]
Hey, sorry for the late reply work is crazy busy right now. This looks great, thanks for adding the api updates an other bits in. Will get this tested and pushed tonight :)

**Comment by Izion** [comment]
Had been meaning to ask if I could add you to the contributors list on steam? Seems wrong not having your name up there considering all the work this was to create (and now with updates lol).

**Comment by FeepingCreature** [comment]
Yeah sure, thanks! :)

I'm not sure how long I'll play SE this time around, since it has a habit of crashing every 15 minutes and also there's not much interesting to do.

Kerbal Space Factorio Engineers when... ;.;

**Comment by Izion** [comment]
Great, sent over a friend request. Has also been crashing here but not quite that often, some AI or just something to explore would make a nice addition to keep the game alive but can't see keen doing that :(

"Kerbal Space Factorio Engineers" - Would play the crap out of that lol

Satisfactory is pretty good an worth a look 👍

**Pull request merged**
